# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectPlusPlus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'PFWebViewController'
pod 'Pangu'
pod 'AFNetworking', :git => 'https://github.com/Cee/AFNetworking.git', :branch => 'JSONKit'
pod 'NSDate+TimeAgo'
pod 'YYWebImage'

# User Notification
pod 'AVOSCloud'
pod 'AVOSCloudIM'

pod 'LLSimpleCamera', '~> 4.1'

pod 'Mapbox-iOS-SDK', '~> 3.3.4'

  # Pods for ConnectPlusPlus

end
